openapi: 3.0.0
info:
  title: Ontvangen van notificaties mbt aanvraag levensonderhoud
  description: Ontvangen van notificaties 
  version: 0.9.0
security:
  - apiAuth: []
paths:
  /notificaties:
    post:
      operationId: notificaties_create
      description: Publiceer een notificatie.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        '200':
          description: ''
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
        '401':
          description: Unauthorized
          headers:
            API-version:
              schema:
                type: string
              description: 'Niet geauthoriseerd'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
        '500':
          description: Internal server error
          headers:
            API-version:
              schema:
                type: string
              description: 'Geeft een specifieke API-versie aan in de context van een specifieke aanroep. Voorbeeld: 1.2.1.'
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/Fout'
      tags:
        - notificaties
      security:
       - apiAuth: []
    parameters: []
servers:
  - url: 'localhost'
components:
  securitySchemes:
    apiAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Message:
      required:
        - kanaal
        - hoofdObject
        - resource
        - resourceUrl
        - actie
        - aanmaakdatum
      type: object
      properties:
        # kanaal:
         # title: kanaal
         # description: De naam van het kanaal (`KANAAL.naam`) waar het bericht op moet worden gepubliceerd.
         # type: string
         # maxLength: 50
         # minLength: 1
        hoofdObject:
          title: hoofd object
          description: URL-referentie naar het hoofd object van de publicerende API die betrekking heeft op de `resource`.
          type: string
          format: uri
          minLength: 1
        resource:
          title: resource
          description: De resourcenaam waar de notificatie over gaat.
          type: string
          maxLength: 100
          minLength: 1
        resourceUrl:
          title: resource URL
          description: URL-referentie naar de `resource` van de publicerende API.
          type: string
          format: uri
          minLength: 1
        actie:
          title: actie
          description: De actie die door de publicerende API is gedaan. De publicerende API specificeert de toegestane acties.
          type: string
          maxLength: 100
          minLength: 1
        aanmaakdatum:
          title: aanmaakdatum
          description: Datum en tijd waarop de actie heeft plaatsgevonden.
          type: string
          format: date-time
        kenmerken:
          title: kenmerken
          description: Mapping van kenmerken (sleutel/waarde) van de notificatie. De publicerende API specificeert de toegestane kenmerken.
          type: object
          additionalProperties:
            title: kenmerk
            description: Een waarde behorende bij de sleutel.
            type: string
            maxLength: 1000
            minLength: 1
    Fout:
      required:
        - code
        - title
        - status
        - detail
        - instance
      type: object
      properties:
        type:
          title: Type
          description: 'URI referentie naar het type fout, bedoeld voor developers'
          type: string
        code:
          title: Code
          description: Systeemcode die het type fout aangeeft
          type: string
          minLength: 1
        title:
          title: Title
          description: Generieke titel voor het type fout
          type: string
          minLength: 1
        status:
          title: Status
          description: De HTTP status code
          type: integer
        detail:
          title: Detail
          description: 'Extra informatie bij de fout, indien beschikbaar'
          type: string
          minLength: 1
        instance:
          title: Instance
          description: 'URI met referentie naar dit specifiek voorkomen van de fout. Deze kan gebruikt worden in combinatie met server logs, bijvoorbeeld.'
          type: string
          minLength: 1